sudo: false
language: ruby
env:
  global:
    - APP_SECRET_TOKEN=b2724973fd81c2f4ac0f92ac48eb3f0152c4a11824c122bcf783419a4c51d8b9bba81c8ba6a66c7de599677c7f486242cf819775c433908e77c739c5c8ae118d
    - COVERALLS_ENDPOINT=https://4a831a25.ngrok.com
  matrix:
    - DATABASE_ADAPTER=mysql2
    - DATABASE_ADAPTER=postgresql DATABASE_USERNAME=postgres ON_HEROKU=true
rvm:
- 2.0.0
- 2.1.5
- 1.9.3
cache: bundler
bundler_args: --without development production
before_script:
- bundle exec rake db:create db:migrate
script: bundle exec rake
